@startuml name
class Simulator
Simulator : int time
Simulator : int day
Simulator : int task
Simulator : int productNum
Simulator : int tradingVolume
Simulator : double cash
Simulator : double initial_cash
Simulator : double myTotalAsset
Simulator : vector<Product*> p
Simulator : Simulator()
Simulator : "~"Simulator()
Simulator : 

class Product
class Stock
class Bitcoin

Product o-- Simulator
Product <|-- Stock
Product <|-- Bitcoin

@enduml